### ISSUE TITLE
Metadata - Spatial resolution for raster data: Add the specific resolution (e.g. 1km2) instead of "Nepal"

### ISSUE THREAD

**Issue by Dimitrismentis** [kartoza/clean-cooking-platform#406]

**Comment by babakkhavari** [comment]
@dimasciput 

The resolution is read from here I think 
![image](https://user-images.githubusercontent.com/35455877/161920771-3845ef91-9cc1-4915-bd97-30c97c76555f.png)

So, the way it is set up now the raster can not get resolutions other than countries, regions or "global" can you help here.

**Comment by dimasciput** [comment]
@babakkhavari I updated the code so this can be read from keywords metadata : 
![image](https://user-images.githubusercontent.com/1979569/163325967-3e312133-cc2c-4329-a4a2-8608c9b005c9.png)

You need to write it with this format : `spatial_resolution:{resolution}`.

**Comment by babakkhavari** [comment]
@dimasciput we have started to implement these things in the platform, but we still get the region on the explorer when open the metadata.
